# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publiched_date',
            new_name='published_date',
        ),
    ]
